### ISSUE TITLE
Implement more logging

### ISSUE THREAD

**Issue by apfong** [UCLA-CS130/Mr.-Robot-et-al.#32]
Not required for Assignment 4, but would be helpful to have. We could use either [Google's Logging Library](https://www.google.com/url?q=https://github.com/google/glog&sa=D&ust=1486015918859000&usg=AFQjCNEv2kxhdrEOxe5H9QeivNU-NjuAPA) or [Boost Logging](https://www.google.com/url?q=http://www.boost.org/doc/libs/1_62_0/libs/log/doc/html/log/tutorial.html&sa=D&ust=1486015918859000&usg=AFQjCNEUPyG8_Ct27A_S0PA21DUqwHxIDA) (particularly `BOOST_LOG_TRIVIAL`)

**Comment by KyCodeHuynh** [comment]
We have not needed any additional logging beyond standard print statements. These are inconvenient to enable/disable quickly, but otherwise adding a logging library now would distract from new features.
