### ISSUE TITLE
Better memory management

### ISSUE THREAD

**Issue by kfrankc** [UCLA-CS130/Mr.-Robot-et-al.#35]
Currently, we don't have a destructor in our EchoRequestHandler class. This won't cause problems right now, since we are manually freeing created pointers, but we'll need to build a better system for memory management later.

**Comment by KyCodeHuynh** [comment]
PR #58 merged in our massive Lightning API refactor, which included creating long-lived request handlers that are tracked by `unique_ptr`'s.
