### ISSUE TITLE
Use map::find() instead of map::at() for lookup

### ISSUE THREAD

**Issue by KyCodeHuynh** [UCLA-CS130/Mr.-Robot-et-al.#48]
[Here](https://github.com/UCLA-CS130/Mr.-Robot-et-al./blob/request-router-refactor/server_config.cc#L96), we try an `at()` and catch the exception to know when something is not in the map. To avoid exception-handling altogether, we can use `map::find()`, which returns an iterator instead, which could be equal to [`map::end()`](http://www.cplusplus.com/reference/map/map/end/) for when a key is not present.

**Comment by apfong** [comment]
Addressed in [PR #50](https://github.com/UCLA-CS130/Mr.-Robot-et-al./pull/50)
