### ISSUE TITLE
Write contributor documentation

### ISSUE THREAD

**Issue by apfong** [UCLA-CS130/Mr.-Robot-et-al.#52]
From spec:

> Because everyone is using the same API, students from other teams should be able to contribute to your project.
>  * A shared API is not enough, however. Potential contributors also need to know things like:
>    * How the source code is laid out.
>    * How to build, test, and run the code.
>
> Edit your README file and add instructions on how to work with your code.

**Comment by apfong** [comment]
Will be addressed by [PR #54](https://github.com/UCLA-CS130/Mr.-Robot-et-al./pull/54)

**Comment by KyCodeHuynh** [comment]
Addressed by PR #54
